CREATE TABLE plans (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nombre VARCHAR(100) NOT NULL,
                       precio DECIMAL(10,2) NOT NULL,
                       duracion_dias INT NOT NULL,
                       descripcion VARCHAR(255)
);

CREATE TABLE memberships (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_id BIGINT NOT NULL,
                             plan_id BIGINT NOT NULL,
                             fecha_inicio DATE NOT NULL,
                             fecha_vencimiento DATE NOT NULL,
                             estado VARCHAR(50) NOT NULL
);