CREATE TABLE qr_data (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         access_token_id BIGINT NOT NULL,
                         contenido_qr VARCHAR(255) NOT NULL,
                         imagen_base64 CLOB NOT NULL,
                         fecha_creacion TIMESTAMP NOT NULL,
                         vigente BOOLEAN NOT NULL
);