CREATE TABLE gym_classes (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nombre VARCHAR(100) NOT NULL,
                             descripcion VARCHAR(255),
                             entrenador_nombre VARCHAR(100),
                             branch_id BIGINT NOT NULL,
                             capacidad_maxima INT NOT NULL
);

CREATE TABLE class_reservations (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    user_id BIGINT NOT NULL,
                                    class_id BIGINT NOT NULL,
                                    fecha_reserva TIMESTAMP NOT NULL,
                                    estado VARCHAR(50) NOT NULL
);