CREATE TABLE notifications (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               destinatario_id BIGINT NOT NULL,
                               tipo VARCHAR(50) NOT NULL,
                               mensaje VARCHAR(255) NOT NULL,
                               creado_en TIMESTAMP NOT NULL
);