spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: branch-service
          uri: lb://branch-service
          predicates:
            - Path=/api/branches/**
        - id: membership-service
          uri: lb://membership-service
          predicates:
            - Path=/api/membership/**
        - id: access-service
          uri: lb://access-service
          predicates:
            - Path=/api/access/**
        - id: qr-generator-service
          uri: lb://qr-generator-service
          predicates:
            - Path=/api/qr/**
        - id: capacity-service
          uri: lb://capacity-service
          predicates:
            - Path=/api/capacity/**
        - id: class-service
          uri: lb://class-service
          predicates:
            - Path=/api/classes/**
        - id: routine-service
          uri: lb://routine-service
          predicates:
            - Path=/api/routines/**
        - id: equipment-service
          uri: lb://equipment-service
          predicates:
            - Path=/api/equipment/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notify/**

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    cl.joaedu: DEBUG
    org.springframework.cloud.gateway: DEBUG
