CREATE TABLE routines (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id BIGINT NOT NULL,
                          nombre VARCHAR(100) NOT NULL,
                          objetivo VARCHAR(150),
                          creado_por VARCHAR(100),
                          fecha_creacion DATE NOT NULL
);

CREATE TABLE routine_exercises (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   routine_id BIGINT NOT NULL,
                                   nombre_ejercicio VARCHAR(100) NOT NULL,
                                   series INT NOT NULL,
                                   repeticiones INT NOT NULL,
                                   descanso_segundos INT
);