CREATE TABLE access_tokens (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL,
                               branch_id BIGINT NOT NULL,
                               qr_code VARCHAR(255) NOT NULL UNIQUE,
                               fecha_expiracion TIMESTAMP NOT NULL,
                               estado VARCHAR(50) NOT NULL
);

CREATE TABLE access_logs (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_id BIGINT NOT NULL,
                             branch_id BIGINT NOT NULL,
                             tipo VARCHAR(30) NOT NULL,
                             timestamp TIMESTAMP NOT NULL
);