CREATE TABLE equipment (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nombre VARCHAR(100) NOT NULL,
                           categoria VARCHAR(100) NOT NULL,
                           branch_id BIGINT NOT NULL,
                           estado VARCHAR(50) NOT NULL
);