CREATE TABLE capacity_counters (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   branch_id BIGINT NOT NULL UNIQUE,
                                   personas_actuales INT NOT NULL,
                                   capacidad_maxima INT NOT NULL,
                                   porcentaje_ocupacion DOUBLE NOT NULL,
                                   ultima_actualizacion TIMESTAMP NOT NULL
);